[package]
name = "gcstool"
version = "0.1.0"
authors = ["Thomas Hurst <tom@hur.st>"]

[dependencies]
sha1 = "0.6.0"
bytecount = "0.3.1"
byteorder = "1.2.2"

[dependencies.clap]
version = "~2.31.2"
default-features = false

[profile.release]
lto = true
